name: Feature Request
description: Propose a new capability or improvement
labels: ["type/feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user/developer problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Outline the behavior and API/UX impact.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: Rollout risks, migration concerns, or policy/security impact.
